apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: user-management
  name: user-management
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-management
    spec:
      containers:
      - image: sachinthadezoysa/usermanagement:v4
        imagePullPolicy: IfNotPresent
        name: user-management
        ports:
        - containerPort: 3000

