name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
            -
              name: Checkout 
              uses: actions/checkout@v2
            -
              name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            -
              name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/usermanagement:latest
                
            - 
              name: Kuberentes (k8s) cli - kubectl
              uses: actions-hub/kubectl@v1.21.2
      
            
            -
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                args: get pods
              
            

